package com.scaler.bms.constants;

public enum TransactionStatus {
    AUTH_STARTED,
    AUTH_IN_PROGRESS,
    AUTH_COMPLETED,
    MINIMUM_BALANCE_VALIDATION_SUCCESS,
    MINIMUM_BALANCE_VALIDATION_FAIL,
    AUTH_ERROR,
    CARD_VALIDATION_ERROR,
    CARD_VALIDATION_SUCCESS,
    REFUND_INITIATED,
    REFUND_IN_PROGRESS,
    REFUND_COMPLETED,
    REFUND_CANCELLED_ERROR
}
